version: '3.9'
services:
    dockerlm:
        image: 'dockerlm:latest'
        tty: true
        stdin_open: true
        container_name: dockerlm
        ports:
            - '1700:1700'
        mac_address: '00:14:4f:8d:24:cc'
        hostname: gaia
        volumes:
            - '.\license.dat:/opt/license.dat' #WIN PATH
#            - './license.dat:/opt/license.dat' #UNIX PATH
        user: root
