services:
    dockerlm:
        image: dockerlm:env
        container_name: ${FLEXLM_HOSTNAME:-flexlm-server}
        ports:
            - "${FLEXLM_PORT:-27000}:27000"
        environment:
            - VENDOR_NAME=${VENDOR_NAME:-default_vendor}
        mac_address: ${FLEXLM_MAC:-00:14:4f:8d:24:cc}
        hostname: ${FLEXLM_HOSTNAME:-flexlm-server}
        volumes:
            - ./licenses:/opt/flexlm/licenses
            - ./vendors:/opt/flexlm/vendors:ro
            - ./logs:/opt/flexlm/logs
            - ./start-flexlm.sh:/opt/flexlm/bin/start-flexlm.sh:ro
        restart: unless-stopped
        cap_add:
        - NET_ADMIN
