version: '3.9'
services:
    dockerlm:
        image: 'ghcr.io/whit3str/dockerlm:latest'
        tty: true
        stdin_open: true
        container_name: dockerlm_VENDOR #Optional, specify if you aim to run several containers
        ports:
            - 'LMGRDPORT:LMGRDPORT'
            - 'VENDORPORT:VENDORPORT'
        networks:
            default:
                mac_address: MAC@ #Fill correct value
        hostname: HOSTNAME #Fill correct value
        volumes:
            - '/path/to/license.dat:/opt/license.dat' #UNIX PATH